"""empty message

Revision ID: 136d4ba25478
Revises: 32a30cfd2a86
Create Date: 2021-04-13 14:09:38.032025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136d4ba25478'
down_revision = '32a30cfd2a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Project', sa.Column('content', sa.String(length=200), nullable=True))
    op.add_column('Project', sa.Column('image', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Project', 'image')
    op.drop_column('Project', 'content')
    # ### end Alembic commands ###
