"""empty message

Revision ID: 459d2980501b
Revises: 136d4ba25478
Create Date: 2021-04-14 13:07:40.238748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459d2980501b'
down_revision = '136d4ba25478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'image')
    # ### end Alembic commands ###
