"""empty message

Revision ID: 98a9db6d959d
Revises: d5bdac970765
Create Date: 2021-04-14 16:01:30.399887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a9db6d959d'
down_revision = 'd5bdac970765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Project', sa.Column('url', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Project', 'url')
    # ### end Alembic commands ###
