"""empty message

Revision ID: d5bdac970765
Revises: 459d2980501b
Create Date: 2021-04-14 15:55:41.525463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5bdac970765'
down_revision = '459d2980501b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Blog', sa.Column('url', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Blog', 'url')
    # ### end Alembic commands ###
